[project]
name = "naq"
version = "0.1.2"
description = "A simple and lightweight NATS queue worker"
readme = "README.md"
authors = [
    { name = "legout", email = "ligno.blades@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "nats-py>=2.6.0",
    "cloudpickle>=2.0.0",
    "typer>=0.9.0", # Add typer dependency
    "loguru>=0.7.0",
    "croniter>=1.4.0", # Add croniter
]

[project.scripts]
naq = "naq.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython>=9.0.2",
]
